//notification types
export const  NotificationActionType = {
	NOTIFICATION_SUCCESS_MESSAGE :"NOTIFICATION_SUCCESS_MESSAGE",
	NOTIFICATION_ERROR_MESSAGE:"NOTIFICATION_ERROR_MESSAGE"
};



export const AuthActionType={
	AUTH_LOGIN_TYPE:"AUTH_LOGIN_TYPE",
	AUTH_LOGIN_TYPE_INIT:"AUTH_LOGIN_TYPE_INIT",
	AUTH_LOGIN_TYPE_SUCCESS:"AUTH_LOGIN_TYPE_SUCCESS",

	AUTH_LOGOUT_TYPE :"AUTH_LOGOUT_TYPE",
	AUTH_LOGOUT_TYPE_INIT:"AUTH_LOGOUT_TYPE_INIT",
	AUTH_LOGOUT_TYPE_SUCCESS:"AUTH_LOGOUT_TYPE_SUCCESS",

}

//permission types
export const PermissionActionType = {
	PERMISSION_LIST_TYPE : "PERMISSION_LIST_TYPE",
	PERMISSION_LIST_TYPE_INIT : "PERMISSION_LIST_TYPE_INIT",
	PERMISSION_LIST_TYPE_SUCCESS : "PERMISSION_LIST_TYPE_SUCCESS",

	PERMISSION_CREATE_TYPE :"PERMISSION_CREATE_TYPE",
	PERMISSION_CREATE_TYPE_INIT : "PERMISSION_CREATE_TYPE_INIT",
	PERMISSION_CREATE_TYPE_SUCCESS:"PERMISSION_CREATE_TYPE_SUCCESS",

	PERMISSION_EDIT_TYPE : "PERMISSION_EDIT_TYPE",
	PERMISSION_EDIT_TYPE_SUCCESS : "PERMISSION_EDIT_TYPE_SUCCESS",

	PERMISSION_UPDATE_TYPE : "PERMISSION_UPDATE_TYPE",
	PERMISSION_UPDATE_TYPE_INIT :"PERMISSION_UPDATE_TYPE_INIT",
	PERMISSION_UPDATE_TYPE_SUCCESS : "PERMISSION_UPDATE_TYPE_SUCCESS",

	PERMISSION_DELETE_TYPE :"PERMISSION_DELETE_TYPE",
	PERMISSION_DELETE_TYPE_INIT: "PERMISSION_DELETE_TYPE_INIT",
	PERMISSION_DELETE_TYPE_SUCCESS : "PERMISSION_DELETE_TYPE_SUCCESS",

	PERMISSION_ROUTE_LIST_TYPE :"PERMISSION_ROUTE_LIST_TYPE",
	PERMISSION_ROUTE_LIST_TYPE_INIT : "PERMISSION_ROUTE_LIST_TYPE_INIT",
	PERMISSION_ROUTE_LIST_TYPE_SUCCESS:"PERMISSION_ROUTE_LIST_TYPE_SUCCESS"

}


export const RoleActionType = {
	ROLE_LIST_TYPE : "ROLE_LIST_TYPE",
	ROLE_LIST_TYPE_INIT : "ROLE_LIST_TYPE_INIT",
	ROLE_LIST_TYPE_SUCCESS : "ROLE_LIST_TYPE_SUCCESS",

	ROLE_CREATE_TYPE :"ROLE_CREATE_TYPE",
	ROLE_CREATE_TYPE_INIT : "ROLE_CREATE_TYPE_INIT",
	ROLE_CREATE_TYPE_SUCCESS:"ROLE_CREATE_TYPE_SUCCESS",

	ROLE_EDIT_TYPE : "ROLE_EDIT_TYPE",
	ROLE_EDIT_TYPE_SUCCESS : "ROLE_EDIT_TYPE_SUCCESS",

	ROLE_UPDATE_TYPE : "ROLE_UPDATE_TYPE",
	ROLE_UPDATE_TYPE_INIT :"ROLE_UPDATE_TYPE_INIT",
	ROLE_UPDATE_TYPE_SUCCESS : "ROLE_UPDATE_TYPE_SUCCESS",

	ROLE_DELETE_TYPE :"ROLE_DELETE_TYPE",
	ROLE_DELETE_TYPE_INIT: "ROLE_DELETE_TYPE_INIT",
	ROLE_DELETE_TYPE_SUCCESS : "ROLE_DELETE_TYPE_SUCCESS",
}