//notification types
export const  NotificationActionType = {
	NOTIFICATION_SUCCESS_MESSAGE :"NOTIFICATION_SUCCESS_MESSAGE",
	NOTIFICATION_ERROR_MESSAGE:"NOTIFICATION_ERROR_MESSAGE"
};



export const AuthActionType={
	AUTH_LOGIN_TYPE:"AUTH_LOGIN_TYPE",
	AUTH_LOGIN_TYPE_INIT:"AUTH_LOGIN_TYPE_INIT",
	AUTH_LOGIN_TYPE_SUCCESS:"AUTH_LOGIN_TYPE_SUCCESS",

	AUTH_LOGOUT_TYPE :"AUTH_LOGOUT_TYPE",
	AUTH_LOGOUT_TYPE_INIT:"AUTH_LOGOUT_TYPE_INIT",
	AUTH_LOGOUT_TYPE_SUCCESS:"AUTH_LOGOUT_TYPE_SUCCESS",

}

//permission types
export const PermissionActionType = {
	PERMISSION_LIST_TYPE : "PERMISSION_LIST_TYPE",
	PERMISSION_LIST_TYPE_INIT : "PERMISSION_LIST_TYPE_INIT",
	PERMISSION_LIST_TYPE_SUCCESS : "PERMISSION_LIST_TYPE_SUCCESS",
	PERMISSION_LIST_TYPE_FAILED:"PERMISSION_LIST_TYPE_FAILED",

	PERMISSION_CREATE_TYPE :"PERMISSION_CREATE_TYPE",
	PERMISSION_CREATE_TYPE_INIT : "PERMISSION_CREATE_TYPE_INIT",
	PERMISSION_CREATE_TYPE_SUCCESS:"PERMISSION_CREATE_TYPE_SUCCESS",
	PERMISSION_CREATE_TYPE_FAILED:"PERMISSION_CREATE_TYPE_FAILED",

	PERMISSION_EDIT_TYPE : "PERMISSION_EDIT_TYPE",
	PERMISSION_EDIT_TYPE_SUCCESS : "PERMISSION_EDIT_TYPE_SUCCESS",
	PERMISSION_EDIT_TYPE_FAILED : "PERMISSION_EDIT_TYPE_FAILED",

	PERMISSION_UPDATE_TYPE : "PERMISSION_UPDATE_TYPE",
	PERMISSION_UPDATE_TYPE_INIT :"PERMISSION_UPDATE_TYPE_INIT",
	PERMISSION_UPDATE_TYPE_SUCCESS : "PERMISSION_UPDATE_TYPE_SUCCESS",
	PERMISSION_UPDATE_TYPE_FAILED : "PERMISSION_UPDATE_TYPE_FAILED",

	PERMISSION_DELETE_TYPE :"PERMISSION_DELETE_TYPE",
	PERMISSION_DELETE_TYPE_INIT: "PERMISSION_DELETE_TYPE_INIT",
	PERMISSION_DELETE_TYPE_SUCCESS : "PERMISSION_DELETE_TYPE_SUCCESS",
	PERMISSION_DELETE_TYPE_FAILED : "PERMISSION_DELETE_TYPE_FAILED",

	PERMISSION_ROUTE_LIST_TYPE :"PERMISSION_ROUTE_LIST_TYPE",
	PERMISSION_ROUTE_LIST_TYPE_INIT : "PERMISSION_ROUTE_LIST_TYPE_INIT",
	PERMISSION_ROUTE_LIST_TYPE_SUCCESS:"PERMISSION_ROUTE_LIST_TYPE_SUCCESS",
	PERMISSION_ROUTE_LIST_TYPE_FAILED : "PERMISSION_ROUTE_LIST_TYPE_FAILED",

}

export const RoleActionType = {
	ROLE_LIST_TYPE : "ROLE_LIST_TYPE",
	ROLE_LIST_TYPE_INIT : "ROLE_LIST_TYPE_INIT",
	ROLE_LIST_TYPE_SUCCESS : "ROLE_LIST_TYPE_SUCCESS",
	ROLE_LIST_TYPE_FAILED : "ROLE_LIST_TYPE_FAILED",

	ROLE_CREATE_TYPE :"ROLE_CREATE_TYPE",
	ROLE_CREATE_TYPE_INIT : "ROLE_CREATE_TYPE_INIT",
	ROLE_CREATE_TYPE_SUCCESS:"ROLE_CREATE_TYPE_SUCCESS",
	ROLE_CREATE_TYPE_FAILED : "ROLE_CREATE_TYPE_FAILED",

	ROLE_EDIT_TYPE : "ROLE_EDIT_TYPE",
	ROLE_EDIT_TYPE_SUCCESS : "ROLE_EDIT_TYPE_SUCCESS",
	ROLE_EDIT_TYPE_FAILED : "ROLE_EDIT_TYPE_FAILED",

	ROLE_UPDATE_TYPE : "ROLE_UPDATE_TYPE",
	ROLE_UPDATE_TYPE_INIT :"ROLE_UPDATE_TYPE_INIT",
	ROLE_UPDATE_TYPE_SUCCESS : "ROLE_UPDATE_TYPE_SUCCESS",
	ROLE_UPDATE_TYPE_FAILED : "ROLE_UPDATE_TYPE_FAILED",

	ROLE_DELETE_TYPE :"ROLE_DELETE_TYPE",
	ROLE_DELETE_TYPE_INIT: "ROLE_DELETE_TYPE_INIT",
	ROLE_DELETE_TYPE_SUCCESS : "ROLE_DELETE_TYPE_SUCCESS",
	ROLE_DELETE_TYPE_FAILED : "ROLE_DELETE_TYPE_FAILED",
}

export const UserActionType = {
	USER_LIST_TYPE : "USER_LIST_TYPE",
	USER_LIST_TYPE_INIT : "USER_LIST_TYPE_INIT",
	USER_LIST_TYPE_SUCCESS : "USER_LIST_TYPE_SUCCESS",
	USER_LIST_TYPE_FAILED : "USER_LIST_TYPE_FAILED",

	USER_CREATE_TYPE :"USER_CREATE_TYPE",
	USER_CREATE_TYPE_INIT : "USER_CREATE_TYPE_INIT",
	USER_CREATE_TYPE_SUCCESS:"USER_CREATE_TYPE_SUCCESS",
	USER_CREATE_TYPE_FAILED : "USER_CREATE_TYPE_FAILED",

	USER_EDIT_TYPE : "USER_EDIT_TYPE",
	USER_EDIT_TYPE_SUCCESS : "USER_EDIT_TYPE_SUCCESS",
	USER_EDIT_TYPE_FAILED : "USER_EDIT_TYPE_FAILED",

	USER_UPDATE_TYPE : "USER_UPDATE_TYPE",
	USER_UPDATE_TYPE_INIT :"USER_UPDATE_TYPE_INIT",
	USER_UPDATE_TYPE_SUCCESS : "USER_UPDATE_TYPE_SUCCESS",
	USER_UPDATE_TYPE_FAILED : "USER_UPDATE_TYPE_FAILED",

	USER_DELETE_TYPE :"USER_DELETE_TYPE",
	USER_DELETE_TYPE_INIT: "USER_DELETE_TYPE_INIT",
	USER_DELETE_TYPE_SUCCESS : "USER_DELETE_TYPE_SUCCESS",
	USER_DELETE_TYPE_FAILED : "USER_DELETE_TYPE_FAILED"


}


export const ChatActionType = {
	CHAT_USER_LIST_TYPE : "CHAT_USER_LIST_TYPE",
	CHAT_USER_LIST_TYPE_INIT : "CHAT_USER_LIST_TYPE_INIT",
	CHAT_USER_LIST_TYPE_SUCCESS : "CHAT_USER_LIST_TYPE_SUCCESS",
	CHAT_USER_LIST_TYPE_FAILED  : "CHAT_USER_LIST_TYPE_FAILED"
}